language: node_js
node_js:
  - "0.10.31"
before_install:
  - gem update --system
  - gem install bundler
  - bundle install
before_script:
  - npm install -g gulp
  - npm install -g bower
  - bower install
  - git config --global user.name "Travis-CI"
  - git config --global user.email "jon@linesandwaves.com"
branches:
  only:
  - source
script: gulp travis
env:
  global:
  - GH_REF: github.com/stuntz-strategies/stuntz-strategies.github.io
  - secure: mzaMRpYQptneoX9Ob7hEEjwXIeNVXq2LzWmrCE3en0tWWUufbP+yZtBvBYLnSGGgSpbeJJsZfgss1SVec+9OOr5HuVSdV/9Fzv/nMxo4krphDtdoifo+B7hxy0d+T6EnkXKH5sP8Y7r2gmjsnAyJPmPEBbhtJVeNO5g6/AtyxIQ=
